# Setup
title:               Mao
tagline:             ''
description:         ''
url:                 
baseurl:             ''
paginate:            3
permalink:           /:year/:month/:day/:title

# About/contact
author:
  name:              Mao
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-148145077-1
